### ISSUE TITLE
Scraping voterid

### ISSUE THREAD

**Issue by dphilipsog** [anjesh/election-voters-scraper#1]
Hi, 

I am trying to scrape the data by voter id for only 10 districts. I am relatively new to coding but was hoping you could walk me through the steps you followed to scrape the Election Centers, if possible. 

Thank you!

Dani

**Comment by anjesh** [comment]
Hey. Install the dependency packages using `pip install -r requirements.txt` and then
 uncomment the following lines https://github.com/anjesh/election-voters-scraper/blob/master/run.py#L64-L70 and see what appears

Good luck.

**Comment by dphilipsog** [comment]
Thank you!

**Comment by dphilipsog** [comment]
Hi Anjesh, 

I have not yet run the code, but wanted to ask if you have any recommendations on what type of software/hardware to optimize efficiency?

Thanks,

**Comment by anjesh** [comment]
Any Python based OS would do for this.
